// Mocks generated by Mockito 5.2.0 from annotations
// in surveys/test/main/composites/remote_load_surveys_with_local_fallback_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:surveys/data/cache/cache.dart' as _i2;
import 'package:surveys/data/http/http.dart' as _i3;
import 'package:surveys/data/usecases/load_surveys/local_load_surveys.dart'
    as _i4;
import 'package:surveys/data/usecases/load_surveys/remote_load_surveys.dart'
    as _i7;
import 'package:surveys/domain/entities/entities.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeCacheStorage_0 extends _i1.Fake implements _i2.CacheStorage {}

class _FakeHttpClient_1 extends _i1.Fake implements _i3.HttpClient {}

/// A class which mocks [LocalLoadSurveys].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalLoadSurveys extends _i1.Mock implements _i4.LocalLoadSurveys {
  MockLocalLoadSurveys() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CacheStorage get cacheStorage =>
      (super.noSuchMethod(Invocation.getter(#cacheStorage),
          returnValue: _FakeCacheStorage_0()) as _i2.CacheStorage);
  @override
  _i5.Future<List<_i6.SurveyEntity>> load() =>
      (super.noSuchMethod(Invocation.method(#load, []),
              returnValue:
                  Future<List<_i6.SurveyEntity>>.value(<_i6.SurveyEntity>[]))
          as _i5.Future<List<_i6.SurveyEntity>>);
  @override
  _i5.Future<void> validate() =>
      (super.noSuchMethod(Invocation.method(#validate, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i5.Future<void>);
  @override
  _i5.Future<void> save(List<_i6.SurveyEntity>? surveys) =>
      (super.noSuchMethod(Invocation.method(#save, [surveys]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i5.Future<void>);
}

/// A class which mocks [RemoteLoadSurveys].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteLoadSurveys extends _i1.Mock implements _i7.RemoteLoadSurveys {
  MockRemoteLoadSurveys() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get url =>
      (super.noSuchMethod(Invocation.getter(#url), returnValue: '') as String);
  @override
  _i3.HttpClient get httpClient =>
      (super.noSuchMethod(Invocation.getter(#httpClient),
          returnValue: _FakeHttpClient_1()) as _i3.HttpClient);
  @override
  _i5.Future<List<_i6.SurveyEntity>> load() =>
      (super.noSuchMethod(Invocation.method(#load, []),
              returnValue:
                  Future<List<_i6.SurveyEntity>>.value(<_i6.SurveyEntity>[]))
          as _i5.Future<List<_i6.SurveyEntity>>);
}
